Repository unixorn/ha-mqtt-discoverable, pull requests merged in 2023-02, with the labels that each got.

#14 Fix bad exception text.
  ha_mqtt_discoverable/__init__.py
  pyproject.toml
Labels: bugfix

#19 Update readme with contributor guidelines
  Contributing.md
  README.md
Labels: documentation

#15 Improve Discoverable and BinarySensor classes
  .editorconfig
  .github/workflows/mega-linter.yml
  .github/workflows/python-tests.yml
  .mega-linter.yml
  Contributing.md
  Dockerfile.testing
  README.md
  docker-compose.yml
  ha_mqtt_discoverable/__init__.py
  ha_mqtt_discoverable/cli/device_driver.py
  ha_mqtt_discoverable/device.py
  ha_mqtt_discoverable/sensors.py
  ha_mqtt_discoverable/settings.py
  ha_mqtt_discoverable/utils.py
  poetry.lock
  pyproject.toml
  tests/mosquitto.conf
  tests/test_binary_sensor.py
  tests/test_discoverable.py
  tests/test_sensor.py
Labels: enhancement

#39 Bugfix import error
  Makefile
  README.md
  ha_mqtt_discoverable/__init__.py
  poetry.lock
  pyproject.toml
Labels: documentation, bugfix

#41 Bugfix docker build
  Dockerfile
  Makefile
Labels: bugfix
